info:
  title: Product API
  description: API para la gestión de productos

paths:
  /api/products/productspaginate:
    get:
      summary: Obtener productos paginados
      tags:
        - Productos
      parameters:
        - name: page
          in: query
          description: Número de página
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Número de productos por página
          required: false
          schema:
            type: integer
            default: 10
        - name: sort
          in: query
          description: Ordenar por precio (asc o desc)
          required: false
          schema:
            type: string
        - name: query
          in: query
          description: Consulta de búsqueda
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Productos paginados
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  totalPages:
                    type: integer
                  prevPage:
                    type: integer
                    nullable: true
                  nextPage:
                    type: integer
                    nullable: true
                  page:
                    type: integer
                  hasPrevPage:
                    type: boolean
                  hasNextPage:
                    type: boolean
                  prevLink:
                    type: string
                    nullable: true
                  nextLink:
                    type: string
                    nullable: true
        '500':
          description: Error al obtener los productos paginados

  /api/products/{pid}:
    get:
      summary: Obtener producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
        '500':
          description: Error al obtener el producto

    patch:
      summary: Actualizar producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      requestBody:
        description: Datos a actualizar del producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado
        '400':
          description: Error en la solicitud
        '500':
          description: Error al actualizar el producto

    delete:
      summary: Eliminar producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado
        '404':
          description: Producto no encontrado
        '500':
          description: Error al eliminar el producto

  /api/products:
    post:
      summary: Crear un nuevo producto
      tags:
        - Productos
      requestBody:
        description: Datos del nuevo producto
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado
        '400':
          description: Error en la solicitud
        '500':
          description: Error al crear el producto

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        thumbnail:
          type: array
          items:
            type: string
        category:
          type: string
        brand:
          type: string
        code:
          type: string
        price:
          type: number
        stock:
          type: number
        status:
          type: boolean
        owner:
          type: string
